const assert = require("node:assert/strict")
const P = require("../Preferences.js")
assert.deepEqual(P.fromSettings({}, "nb_NO"), {language: "nb", units: "metric", automaticLocation: false, animations: true})
assert.deepEqual(P.fromSettings({}, "en_GB"), {language: "en", units: "metric", automaticLocation: false, animations: true})
assert.deepEqual(P.fromSettings({language: "en", units: "imperial", automaticLocation: true, animations: false}, "nb_NO"), {language: "en", units: "imperial", automaticLocation: true, animations: false})
assert.equal(P.fromSettings({automaticLocation: "true"}).automaticLocation, false)
assert.equal(P.fromSettings({language: "invalid"}, "nn_NO").language, "nb")
assert.equal(P.fromSettings(null).language, "en")
assert.equal(P.fromSettings([]).animations, true)
assert.equal(P.temperature(0, "imperial"), "32°")
assert.equal(P.temperature(-40, "imperial"), "-40°")
assert.equal(P.temperature(14.2, "metric"), "14°")
assert.equal(P.precipitation(25.4, "imperial"), "1 in")
assert.equal(P.precipitation(1.25, "metric"), "1.3 mm")
assert.equal(P.precipitation(0, "imperial"), "0 in")
assert.equal(P.wind(10, "imperial", "en"), "22 mph")
assert.equal(P.wind(10, "metric", "en"), "36 km/h")
assert.equal(P.wind(10, "metric", "nb"), "36 km/t")
for (const value of [null, undefined, NaN, Infinity]) {
  assert.equal(P.temperature(value, "imperial"), "—")
  assert.equal(P.precipitation(value, "imperial"), "—")
  assert.equal(P.wind(value, "imperial", "en"), "—")
}
assert.equal(P.text("Delvis skyet", "en"), "Partly cloudy")
assert.equal(P.text("Delvis skyet", "nb"), "Delvis skyet")
assert.equal(P.age("2026-09-24T10:00:00Z", new Date("2026-09-24T10:31:00Z"), "en"), "31 min ago")
assert.equal(P.age("2026-09-24T10:00:00Z", new Date("2026-09-24T10:31:00Z"), "nb"), "31 min siden")
const Model = require("../Model.js")
for (const weight of ["light", "", "heavy"])
  for (const precipitation of ["rain", "snow", "sleet"])
    for (const showers of ["", "showers"])
      for (const thunder of ["", "andthunder"]) {
        const symbol = weight + precipitation + showers + thunder + "_night"
        const description = Model.descriptionForSymbol(symbol)
        assert.notEqual(description, symbol.replace(/_night$/, ""), symbol)
        assert.notEqual(P.text(description, "en"), description, symbol)
      }
assert.equal(P.text(Model.descriptionForSymbol("lightssleetshowersandthunder_day"), "en"), "Light sleet and thunder")
console.log("Weather preferences, translations and unit conversion tests passed.")
